import type { Guest, WeddingSummary, WeddingTask } from "@/types";
import { daysUntil } from "@/lib/date-time";

const weddingDateIso = "2026-06-30";

// Demo data keeps every proposed screen reviewable while the matching API modules are built.
export const currentWedding: WeddingSummary = {
  id: "ruth-izzy",
  title: "Our celebration",
  partnerNames: "Ruth & Izzy",
  date: "30 May 2026",
  weddingDateIso,
  venue: "Shepstone Gardens",
  city: "Randburg",
  daysRemaining: daysUntil(weddingDateIso),
  progress: 68,
  access: "Owner",
};

export const weddingStats = [
  { label: "Budget remaining", value: "R 184,500", detail: "of R 520,000", tone: "rose" },
  { label: "Guests attending", value: "118", detail: "of 164 invited", tone: "sage" },
  { label: "Tasks completed", value: "42", detail: "14 still open", tone: "gold" },
  { label: "Vendors confirmed", value: "8", detail: "3 awaiting response", tone: "blue" },
] as const;

export const guests: Guest[] = [
  {
    id: 1,
    name: "Naledi Molefe",
    group: "Bride's family",
    email: "naledi@example.com",
    phoneNumber: "+27821234501",
    isCouple: false,
    hasChildren: false,
    status: "Attending",
    meal: "Vegetarian",
    table: "Table 04",
  },
  {
    id: 2,
    name: "Daniel Khumalo",
    group: "Groom's friends",
    email: "daniel@example.com",
    phoneNumber: "+27821234502",
    isCouple: false,
    hasChildren: false,
    status: "Pending",
    meal: "Not selected",
    table: "Unassigned",
  },
  {
    id: 3,
    name: "Zoe Williams",
    group: "Friends",
    email: "zoe@example.com",
    phoneNumber: "+27821234503",
    isCouple: true,
    hasChildren: false,
    status: "Attending",
    meal: "Standard",
    table: "Table 08",
  },
  {
    id: 4,
    name: "Mandla Dube",
    group: "Groom's family",
    email: "mandla@example.com",
    phoneNumber: "+27821234504",
    isCouple: false,
    hasChildren: true,
    status: "Declined",
    meal: "—",
    table: "—",
  },
  {
    id: 5,
    name: "Aisha Patel",
    group: "Friends",
    email: "aisha@example.com",
    phoneNumber: "+27821234505",
    isCouple: true,
    hasChildren: true,
    status: "Attending",
    meal: "Halaal",
    table: "Table 08",
  },
];

export const tasks: WeddingTask[] = [
  {
    id: 1,
    title: "Approve the final floral concept",
    category: "Décor",
    due: "Today",
    assignee: "Ruth",
    priority: "High",
    complete: false,
  },
  {
    id: 2,
    title: "Confirm guest transport schedule",
    category: "Logistics",
    due: "16 Sep",
    assignee: "Lerato",
    priority: "Medium",
    complete: false,
  },
  {
    id: 3,
    title: "Send menu choices to caterer",
    category: "Food & drinks",
    due: "18 Sep",
    assignee: "Izzy",
    priority: "High",
    complete: false,
  },
  {
    id: 4,
    title: "Review ceremony music shortlist",
    category: "Entertainment",
    due: "20 Sep",
    assignee: "Ruth",
    priority: "Low",
    complete: true,
  },
  {
    id: 5,
    title: "Pay venue balance",
    category: "Payments",
    due: "24 Sep",
    assignee: "Izzy",
    priority: "High",
    complete: false,
  },
];

export const upcomingEvents = [
  {
    day: "15",
    month: "SEP",
    title: "Final menu tasting",
    meta: "11:00 · Olive & Oak Catering",
    color: "sage",
  },
  {
    day: "18",
    month: "SEP",
    title: "Venue walkthrough",
    meta: "14:30 · Shepstone Gardens",
    color: "rose",
  },
  { day: "21", month: "SEP", title: "Dress fitting", meta: "10:00 · Rosebank", color: "gold" },
];

export const vendors = [
  {
    name: "Daniel West Wedding Photography & Videography",
    category: "Photography",
    rating: "4.9",
    price: "Quote required",
    status: "Confirmed",
    initials: "DW",
    tone: "rose",
  },
  {
    name: "JC Crafford Photo and Video",
    category: "Photography",
    rating: "4.8",
    price: "Quote required",
    status: "Confirmed",
    initials: "JC",
    tone: "rose",
  },
  {
    name: "Nicole Moore Photography",
    category: "Photography",
    rating: "5.0",
    price: "Quote required",
    status: "Shortlisted",
    initials: "NM",
    tone: "rose",
  },
  {
    name: "Judith Belle",
    category: "Photography",
    rating: "5.0",
    price: "Quote required",
    status: "Confirmed",
    initials: "JB",
    tone: "rose",
  },
  {
    name: "Mon Chéri Photography",
    category: "Photography",
    rating: "4.9",
    price: "From R 14,900",
    status: "Confirmed",
    initials: "MC",
    tone: "rose",
  },
  {
    name: "Quantum Photography",
    category: "Photography",
    rating: "4.8",
    price: "From R 4,300",
    status: "Shortlisted",
    initials: "QP",
    tone: "rose",
  },
  {
    name: "Petro Hansen Photography",
    category: "Photography",
    rating: "4.9",
    price: "From R 15,000",
    status: "Quote received",
    initials: "PH",
    tone: "rose",
  },
  {
    name: "Lady May Photography",
    category: "Photography",
    rating: "4.9",
    price: "From R 10,500",
    status: "Confirmed",
    initials: "LM",
    tone: "rose",
  },

  {
    name: "MCW Spitbraai Party Caterers",
    category: "Catering",
    rating: "5.0",
    price: "Quote required",
    status: "Confirmed",
    initials: "MC",
    tone: "sage",
  },
  {
    name: "The Imagination Box Catering",
    category: "Catering",
    rating: "4.9",
    price: "Quote required",
    status: "Shortlisted",
    initials: "IB",
    tone: "sage",
  },
  {
    name: "Catering By Sindi",
    category: "Catering",
    rating: "5.0",
    price: "Quote required",
    status: "Confirmed",
    initials: "CS",
    tone: "sage",
  },
  {
    name: "Spit Braai Caterers - Hungry Panda",
    category: "Catering",
    rating: "4.8",
    price: "Quote required",
    status: "Shortlisted",
    initials: "HP",
    tone: "sage",
  },
  {
    name: "Intiem Weddings",
    category: "Catering",
    rating: "4.9",
    price: "From R 720 / guest",
    status: "Confirmed",
    initials: "IW",
    tone: "sage",
  },

  {
    name: "PETAL&POST Johannesburg/Pretoria",
    category: "Florist",
    rating: "4.9",
    price: "Quote required",
    status: "Confirmed",
    initials: "PP",
    tone: "gold",
  },
  {
    name: "Caar'i Flora",
    category: "Florist",
    rating: "4.6",
    price: "Quote required",
    status: "Shortlisted",
    initials: "CF",
    tone: "gold",
  },
  {
    name: "NetFlorist",
    category: "Florist",
    rating: "4.4",
    price: "From R 495",
    status: "Confirmed",
    initials: "NF",
    tone: "gold",
  },

  {
    name: "Cream Cheese Premier DJs & Events",
    category: "Music & DJ",
    rating: "5.0",
    price: "Quote required",
    status: "Confirmed",
    initials: "CC",
    tone: "blue",
  },
  {
    name: "Jozi Disco",
    category: "Music & DJ",
    rating: "5.0",
    price: "Quote required",
    status: "Shortlisted",
    initials: "JD",
    tone: "blue",
  },
  {
    name: "Gauteng DJ",
    category: "Music & DJ",
    rating: "5.0",
    price: "Quote required",
    status: "Confirmed",
    initials: "GD",
    tone: "blue",
  },
  {
    name: "BeatKulture Entertainment",
    category: "Music & DJ",
    rating: "4.8",
    price: "From R 8,500",
    status: "Confirmed",
    initials: "BK",
    tone: "blue",
  },

  {
    name: "Ethereal Events Co.",
    category: "Planning",
    rating: "5.0",
    price: "Quote required",
    status: "Confirmed",
    initials: "EE",
    tone: "sage",
  },
  {
    name: "Precious Celebrations",
    category: "Planning",
    rating: "4.6",
    price: "Quote required",
    status: "Shortlisted",
    initials: "PC",
    tone: "sage",
  },
  {
    name: "Outlandish Events",
    category: "Planning",
    rating: "5.0",
    price: "Quote required",
    status: "Confirmed",
    initials: "OE",
    tone: "sage",
  },

  {
    name: "Inimitable Wedding Venue",
    category: "Venue",
    rating: "4.8",
    price: "Quote required",
    status: "Confirmed",
    initials: "IW",
    tone: "gold",
  },
  {
    name: "Shepstone Gardens",
    category: "Venue",
    rating: "4.7",
    price: "Quote required",
    status: "Shortlisted",
    initials: "SG",
    tone: "gold",
  },
  {
    name: "The Lakeside - Weddings & Events",
    category: "Venue",
    rating: "4.8",
    price: "Quote required",
    status: "Confirmed",
    initials: "TL",
    tone: "gold",
  },
  {
    name: "Featherwood Farm",
    category: "Venue",
    rating: "4.8",
    price: "From R 27,000",
    status: "Confirmed",
    initials: "FF",
    tone: "gold",
  },

  {
    name: "Daniel West Wedding Photography & Videography",
    category: "Videography",
    rating: "4.9",
    price: "Quote required",
    status: "Confirmed",
    initials: "DW",
    tone: "blue",
  },
  {
    name: "JC Crafford Photo and Video",
    category: "Videography",
    rating: "4.8",
    price: "Quote required",
    status: "Shortlisted",
    initials: "JC",
    tone: "blue",
  },

  {
    name: "BeatKulture Entertainment",
    category: "Entertainment",
    rating: "4.8",
    price: "From R 11,650",
    status: "Confirmed",
    initials: "BK",
    tone: "blue",
  },
  {
    name: "Cream Cheese Premier DJs & Events",
    category: "Entertainment",
    rating: "5.0",
    price: "Quote required",
    status: "Confirmed",
    initials: "CC",
    tone: "blue",
  },
  {
    name: "Jozi Disco",
    category: "Entertainment",
    rating: "5.0",
    price: "Quote required",
    status: "Shortlisted",
    initials: "JD",
    tone: "blue",
  },

  {
    name: "Caar'i Flora",
    category: "Flowers & Decor",
    rating: "4.6",
    price: "Quote required",
    status: "Confirmed",
    initials: "CF",
    tone: "gold",
  },
  {
    name: "PETAL&POST Johannesburg/Pretoria",
    category: "Flowers & Decor",
    rating: "4.9",
    price: "Quote required",
    status: "Shortlisted",
    initials: "PP",
    tone: "gold",
  },
  {
    name: "NetFlorist",
    category: "Flowers & Decor",
    rating: "4.4",
    price: "From R 495",
    status: "Confirmed",
    initials: "NF",
    tone: "gold",
  },

  {
    name: "Intiem Weddings",
    category: "Wedding Package",
    rating: "4.9",
    price: "From R 17,000",
    status: "Confirmed",
    initials: "IW",
    tone: "rose",
  },
  {
    name: "Intiem Weddings",
    category: "Wedding Package",
    rating: "4.9",
    price: "From R 20,500",
    status: "Shortlisted",
    initials: "IW",
    tone: "rose",
  },
  {
    name: "Featherwood Farm",
    category: "Wedding Package",
    rating: "4.8",
    price: "From R 31,500",
    status: "Confirmed",
    initials: "FF",
    tone: "rose",
  },

  {
    name: "MCW Spitbraai Party Caterers",
    category: "Wedding Catering",
    rating: "5.0",
    price: "Quote required",
    status: "Confirmed",
    initials: "MC",
    tone: "sage",
  },
  {
    name: "The Imagination Box Catering",
    category: "Wedding Catering",
    rating: "4.9",
    price: "Quote required",
    status: "Shortlisted",
    initials: "IB",
    tone: "sage",
  },
  {
    name: "Catering By Sindi",
    category: "Wedding Catering",
    rating: "5.0",
    price: "Quote required",
    status: "Confirmed",
    initials: "CS",
    tone: "sage",
  },

  {
    name: "Ethereal Events Co.",
    category: "Wedding Planning",
    rating: "5.0",
    price: "Quote required",
    status: "Confirmed",
    initials: "EE",
    tone: "sage",
  },
  {
    name: "Precious Celebrations",
    category: "Wedding Planning",
    rating: "4.6",
    price: "Quote required",
    status: "Shortlisted",
    initials: "PC",
    tone: "sage",
  },
  {
    name: "Outlandish Events",
    category: "Wedding Planning",
    rating: "5.0",
    price: "Quote required",
    status: "Confirmed",
    initials: "OE",
    tone: "sage",
  },

  {
    name: "Shepstone Gardens",
    category: "Wedding Venue",
    rating: "4.7",
    price: "Quote required",
    status: "Confirmed",
    initials: "SG",
    tone: "gold",
  },
  {
    name: "The Lakeside - Weddings & Events",
    category: "Wedding Venue",
    rating: "4.8",
    price: "Quote required",
    status: "Shortlisted",
    initials: "TL",
    tone: "gold",
  },
  {
    name: "Inimitable Wedding Venue",
    category: "Wedding Venue",
    rating: "4.8",
    price: "Quote required",
    status: "Confirmed",
    initials: "IW",
    tone: "gold",
  },

  {
    name: "Daniel West Wedding Photography & Videography",
    category: "Wedding Photography",
    rating: "4.9",
    price: "Quote required",
    status: "Confirmed",
    initials: "DW",
    tone: "rose",
  },
  {
    name: "Nicole Moore Photography",
    category: "Wedding Photography",
    rating: "5.0",
    price: "Quote required",
    status: "Shortlisted",
    initials: "NM",
    tone: "rose",
  },
  {
    name: "Judith Belle",
    category: "Wedding Photography",
    rating: "5.0",
    price: "Quote required",
    status: "Confirmed",
    initials: "JB",
    tone: "rose",
  },
  {
    name: "Quantum Photography",
    category: "Wedding Photography",
    rating: "4.8",
    price: "From R 8,500",
    status: "Shortlisted",
    initials: "QP",
    tone: "rose",
  },
];

export const budgetCategories = [
  { name: "Venue", amount: 142000, budget: 150000, color: "#8d4656" },
  { name: "Food & drinks", amount: 96500, budget: 130000, color: "#71826b" },
  { name: "Photography", amount: 28000, budget: 35000, color: "#b99052" },
  { name: "Décor & flowers", amount: 44000, budget: 70000, color: "#ad7180" },
  { name: "Other", amount: 25000, budget: 135000, color: "#74859d" },
];
